version: 2

models:
  - name: problem_1
    description: "Tabela com os dados tratados para a resolução do primeiro problema"
    columns:
      - name: id_paciente
        description: "Identificador de paciente"
        tests:
          - unique
          - not_null
      - name: obito
        description: "Indicação de óbito"
      - name: luz_eletrica
        description: "Indicação se possui luz elétrica"
      - name: em_situacao_de_rua
        description: "Indicação se em situação de rua"
      - name: possui_plano_saude
        description: "Indicação se possui plano de saúde"
        description: "Indicação se a família do paciente é beneficiária"

  - name: problem_2
    description: "Tabela com os dados tratados para a resolução do segundo problema"
    columns:
      - name: id_paciente
        description: "Identificador de paciente"
        tests:
          - unique
          - not_null
      - name: frequenta_escola
        description: "Indicação se frequenta escola"

  
  - name: problem_3
    description: "Tabela com os dados tratados para a resolução do terceiro problema"
    columns:
      - name: id_paciente
        description: "Identificador de paciente"
        tests:
          - unique
          - not_null
      - name: crianca_matriculada_creche_pre_escola
        description: "Indicação se a criança está matriculada em creche ou pré-escola"

  - name: problem_4
    description: "Tabela com os dados tratados para a resolução do quarto problema"
    columns:
      - name: id_paciente
        description: "Identificador de paciente"
        tests:
          - unique
          - not_null
      - name: sexo
        description: "Sexo"
      - name: atualizado_em
        description: "Data e hora da última atualização dos dados"

  - name: problem_5
    description: "Tabela com os dados tratados para a resolução do quinto problema"
    columns:
      - name: id_paciente
        description: "Identificador de paciente"
        tests:
          - unique
          - not_null
      - name: tipo
        description: "Identifica se dado veio de fluxo rotineiro ou histórico"

  - name: problem_6-7
    description: "Tabela com os dados tratados para a resolução do sexto e do sétimo problema"
    columns:
      - name: id_paciente
        description: "Identificador de paciente"
        tests:
          - unique
          - not_null
      - name: meios_transporte
        description: "Meios de transporte utilizados"
      - name: doencas_condicoes
        description: "Doenças ou condições de saúde"
      - name: identidade_genero
        description: "Identidade de gênero"
      - name: meios_comunicacao
        description: "Meios de comunicação utilizados"